#!/bin/bash

IMAGE_NAME="pypiserver/pypiserver:latest"
CONTAINER_NAME="pypi-server-container"


if [ "$1" == "-d" ]; then
    read -p "Are you sure to delete the docker container $CONTAINER_NAME? (Y/n) " -n 1 -r
    REPLY=${REPLY:-Y}

    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        if [ "$(docker container ls -a | grep "$CONTAINER_NAME")" ]; then
            echo -e "Clearing the $CONTAINER_NAME"
            docker container rm -v -f $CONTAINER_NAME
        else
            echo -e "$CONTAINER_NAME does not exist"
        fi
    else
        echo -e "\nAborted"
    fi

    exit 0
fi

# -a . -P . allow any username and password
if [ ! "$(docker container ls -a | grep "$CONTAINER_NAME")" ]; then
    echo "$CONTAINER_NAME does not exist. Creating a new one..."
    docker run --name $CONTAINER_NAME \
        -d -p 8080:8080 \
        $IMAGE_NAME -a . -P .
else
    echo "$CONTAINER_NAME already exists. Starting the container..."
    docker start $CONTAINER_NAME
fi