#!/bin/bash

git reset --soft HEAD~
git add-commit -m "Updated the python-excercise-repository"
git push -f

echo -e "\nWait a second ..." && sleep 1

echo "Changes in the last commit:"
git diff HEAD~1 HEAD --name-only --color && echo

git log -2