#!/bin/bash

task_raw=$(aws ecs run-task \
  --task-definition C02PYTHONWORDPDFFARGATEStackC02PYTHONWORDPDFFARGATEStackFARGATEA1C3D208 \
  --launch-type FARGATE \
  --cluster C02-PYTHON-WORD-PDF-FARGATE-Stack-CLUSTER \
  --network-configuration \
    "awsvpcConfiguration={subnets=[subnet-036858aaddbf402c7,subnet-054e62a990450cb1a],securityGroups=[sg-0c164a9c96dda2a91],assignPublicIp=ENABLED}")

taskArn=$(echo $task_raw | jq '.tasks[0].taskArn')

echo -e "Task Started\n$taskArn"
